apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-game-deployment
  labels:
    app: fishing-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishing-game
  template:
    metadata:
      labels:
        app: fishing-game
    spec:
      containers:
      - name: fishing-game
        image: hub.ecns.io/devops/fishing:alpha-${BUILD_ID}  # 替换为你实际的镜像名称
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
